apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q791ulruw-python
  janus-idp.io/tekton: q791ulruw-python
  backstage.io/kubernetes-id: q791ulruw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q791ulruw-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
